services:
  - type: web
    name: orbisx-backend
    env: python
    buildCommand: |
      cd backend &&
      pip install -r requirements.txt
    startCommand: cd backend && python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    
  - type: web
    name: orbisx-frontend
    env: node
    buildCommand: |
      cd frontend &&
      npm install &&
      npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_ENV
        value: production

